# SPDX-License-Identifier: BSD-2-Clause-Patent

name: "Ubuntu 20 Images"

# This workflow only runs (on the main branch or on PRs targeted
# at the main branch) and if files inside the Ubuntu-20 directory
# have been modifed/added/removed...

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Build_Image:
      uses: ./.github/workflows/build-image.yaml
      with:
        image_name: "mppl"
        sub_images: ""
