# GitHub Actions Workflow for building and pushing Docker images

# SPDX-License-Identifier: BSD-2-Clause-Patent

# This workflow is intended to be called from another top-level
# workflow. Each set of images (defined in a common Dockerfile)
# should have a matching top-level workflow yaml file.


name: "Build and Push images"

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
        description: "Name of the image to build (= folder name)"
      runs_on:
        type: string
        required: false
        description: "The OS used to build the docker image."
        default: "ubuntu-latest"

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  IMAGE_NAME: ${{ inputs.image_name }}

jobs:
  build-and-push-image:
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        run: echo "short_sha=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
        shell: bash

      - name: Build
        run: |
          IMG=$(tr '[:upper:]' '[:lower:]' <<< "${REGISTRY}/${REPOSITORY}/${IMAGE_NAME}")
          echo "Building Image: ${IMG}:${short_sha}..."
          docker build --tag "${IMG}:${short_sha}" -f Dockerfile .
        shell: bash

      - name: Push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          IMG=$(tr '[:upper:]' '[:lower:]' <<< "${REGISTRY}/${REPOSITORY}/${IMAGE_NAME}")
          echo "Pushing Image: ${IMG}:${short_sha}..."
          docker tag "${IMG}:${short_sha}" "${IMG}:latest"
          docker push "${IMG}:${short_sha}"
          docker push "${IMG}:latest"
        shell: bash


